import Head from "next/head";
import { useMoralis } from "react-moralis";
import Login from "../components/Login";

export default function Home() {
  const { isAuthenticated, logout } = useMoralis();

  if (!isAuthenticated) return <Login />;

  return (
    <div className="">
      <Head>
        <title>MetaVerse </title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <h1>Welcome</h1>
      <button
        className="bg-yellow-500 rounded-lg p-5 font-bold hover:animate-pulse"
        onClick={logout}
      >
        Logout
      </button>
    </div>
  );
}
